sudo: true
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: pypy
before_install:
  - scripts/prepare-travis-ci.sh
install:
  - pip install --upgrade --requirement=requirements-travis.txt
  - LC_ALL=C pip install .
script:
  - make check
  - make full-coverage
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
